追加画面の作成#11
niko1105/lamp_practice pull request #12
Opened 2020-04-26 06:35 UTC by niko1105

購入履歴画面、購入明細画面を作成しました。
ご確認をお願い致します。

2020-04-26 18:28 UTC, thisprodigiousgeek requested changes
完成も間近になってきましたね！
指摘部分の修正と、該当のユーザー以外購入明細をみられなくする処理の実装を行なって仕上げていきましょう！

2020-04-26 18:28 UTC, thisprodigiousgeek commented on www/model/order_detail.php
> +                  order_details.price * order_details.amount as total_price
合計と小計が同じ名前だと少し混乱しやすいかもしれませんね！

2020-04-26 18:28 UTC, thisprodigiousgeek commented on www/model/order_detail.php
> +function select_order($db, $order_id){
他のselect文を実行する関数の名称はどうなっているでしょうか？また、単数形複数形にも気をつけておきましょう！

2020-04-26 18:28 UTC, thisprodigiousgeek commented on www/html/order_detail.php
> +$order_id = get_post('order_id');
今回はGETとPOSTどっちが望ましいでしょうか？

2020-04-27 12:47 UTC, niko1105 commented
再度プッシュしましたので、ご確認をお願い致します。

2020-04-27 13:03 UTC, thisprodigiousgeek requested changes
ほぼ完成していらっしゃいますね！関数名の変更と分岐の整理だけ仕上げておきましょう！

2020-04-27 13:03 UTC, thisprodigiousgeek commented on www/html/order_detail.php
> +$order = get_user_order($db,$order_id);
この関数でのorderの取得条件にuserは関連していませんね！

2020-04-27 13:03 UTC, thisprodigiousgeek commented on www/html/order_detail.php
> +if($user['user_id'] === $order['user_id']){
一致しないときにリダイレクトする形にすればelseは不要になりますね！

2020-04-27 15:45 UTC, niko1105 commented
ご返信いただきありがとうございます。
再度修正しましたのでご確認をお願い致します。

2020-04-27 19:06 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます！

2020-04-27 19:07 UTC, merged