SQLインジェクション対策#3
niko1105/lamp_practice pull request #4
Opened 2020-03-29 14:04 UTC by niko1105

issue#3にて指定したファイルにプリペアードステートメントを活用したエスケープ処理を行いました。
ご確認を宜しくお願い致します。

2020-04-01 11:58 UTC, thisprodigiousgeek requested changes
今回のfetch_queryなどにおける$paramsの意味を理解する必要がありますね！レッスンで確認していきましょう！

2020-04-01 15:19 UTC, niko1105 commented
修正しました。再度ご確認をお願い致します。

2020-04-02 04:46 UTC, thisprodigiousgeek approved these changes
SQLインジェクション対策、しっかり実装していただけましたね！
バインドの仕組み、ばっちり理解できていて素晴らしいです。
マージさせていただきます！

2020-04-02 04:46 UTC, thisprodigiousgeek commented on www/model/cart.php
> +    $params = array(':item_id' => $item_id, ':user_id' => $user_id, ':amount' => $amount);
可読性を高めるため、改行を入れましょう！

2020-04-02 04:46 UTC, merged