CSRF対策実装#5
niko1105/lamp_practice pull request #6
Opened 2020-04-04 10:01 UTC by niko1105

CSRF対策の実装を行いました。ご確認の程、宜しくお願い致します。

2020-04-05 04:46 UTC, thisprodigiousgeek requested changes
まずはトークンの生成と埋め込み、しっかり実装していただけましたね！
トークンの照合については動作確認は行いましたか？
ひとまず想定通りの動作が行われるかどうかを確認するところからスタートしましょう！

2020-04-08 15:10 UTC, niko1105 commented
修正後、再度プッシュを行いましたのでご確認をお願い致します。

2020-04-11 08:26 UTC, thisprodigiousgeek requested changes
CSRFと無関係なファイル追加を削除していただけば完成ですね！
次の課題のファイルだけ削除しておきましょう！

2020-04-11 08:26 UTC, thisprodigiousgeek commented on lamp_dock/append_schema.sql
> +CREATE TABLE purchase_history (
こちらのSQLはこのプルリクエストには不要ですね！次のプルリクエストに含めるようにして、こちらからは削除しましょう！

2020-04-11 12:18 UTC, merged